apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.db.password | quote }}
  DB_PASSWORD: {{ .Values.db.password | quote }}
