apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-db
